# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Facture.o Medicament.o Pharmacien.o Compte.o Administrateur.o Vente.o
LINKOBJ  = main.o Facture.o Medicament.o Pharmacien.o Compte.o Administrateur.o Vente.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Pharmacie.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Facture.o: Facture.cpp
	$(CPP) -c Facture.cpp -o Facture.o $(CXXFLAGS)

Medicament.o: Medicament.cpp
	$(CPP) -c Medicament.cpp -o Medicament.o $(CXXFLAGS)

Pharmacien.o: Pharmacien.cpp
	$(CPP) -c Pharmacien.cpp -o Pharmacien.o $(CXXFLAGS)

Compte.o: Compte.cpp
	$(CPP) -c Compte.cpp -o Compte.o $(CXXFLAGS)

Administrateur.o: Administrateur.cpp
	$(CPP) -c Administrateur.cpp -o Administrateur.o $(CXXFLAGS)

Vente.o: Vente.cpp
	$(CPP) -c Vente.cpp -o Vente.o $(CXXFLAGS)
